apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tests-go-guprdcdl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/github-tests-go-guprdcdl:a102a4ac3737c0032188020781adf058bcaf9361@sha256:7a315665e04d1b8a893084cbde3ca3e865e2341719afd73f6cb78b677fb96c52
          name: container-image
